# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

log_ddirichlet <- function(eta, alpha) {
    .Call(`_sparselca_log_ddirichlet`, eta, alpha)
}

sample_covariance <- function(Ym) {
    .Call(`_sparselca_sample_covariance`, Ym)
}

Mahalanobis <- function(x, center, cov) {
    .Call(`_sparselca_Mahalanobis`, x, center, cov)
}

dmvnrm_arma <- function(x, mean, sigma, logd = FALSE, sumd = FALSE) {
    .Call(`_sparselca_dmvnrm_arma`, x, mean, sigma, logd, sumd)
}

dmvnorm_arma_prec <- function(x, mean, precision, log = FALSE) {
    .Call(`_sparselca_dmvnorm_arma_prec`, x, mean, precision, log)
}

mvrnormArma <- function(n, mu, sigma) {
    .Call(`_sparselca_mvrnormArma`, n, mu, sigma)
}

log_dwishart_sample <- function(Sigma_sample, df, Winv) {
    .Call(`_sparselca_log_dwishart_sample`, Sigma_sample, df, Winv)
}

log_ptheta <- function(Theta, mu, kappa, Sigma_sample) {
    .Call(`_sparselca_log_ptheta`, Theta, mu, kappa, Sigma_sample)
}

log_dirichlet <- function(pvec, alphavec) {
    .Call(`_sparselca_log_dirichlet`, pvec, alphavec)
}

wishartArma_int <- function(nu, V) {
    .Call(`_sparselca_wishartArma_int`, nu, V)
}

iwishartArma_int <- function(nu, S) {
    .Call(`_sparselca_iwishartArma_int`, nu, S)
}

logsumexp_vec <- function(avec) {
    .Call(`_sparselca_logsumexp_vec`, avec)
}

logsumexp <- function(a, b) {
    .Call(`_sparselca_logsumexp`, a, b)
}

normalize_vec <- function(v) {
    .Call(`_sparselca_normalize_vec`, v)
}

normalize_logvec <- function(lv) {
    .Call(`_sparselca_normalize_logvec`, lv)
}

nvec_count <- function(svec, k) {
    .Call(`_sparselca_nvec_count`, svec, k)
}

count_if <- function(c_vec, cval) {
    .Call(`_sparselca_count_if`, c_vec, cval)
}

count_classes <- function(c_vec, Kbig) {
    .Call(`_sparselca_count_classes`, c_vec, Kbig)
}

table_by_class <- function(YY, cvec, Kbig) {
    .Call(`_sparselca_table_by_class`, YY, cvec, Kbig)
}

update_Sigma_ind_mcmc <- function(YY, s, K, theta, df0, prior_Scale) {
    .Call(`_sparselca_update_Sigma_ind_mcmc`, YY, s, K, theta, df0, prior_Scale)
}

update_Sigma_mcmc <- function(YY, s, K, mu0, kappa0, df, Winv) {
    .Call(`_sparselca_update_Sigma_mcmc`, YY, s, K, mu0, kappa0, df, Winv)
}

update_eta <- function(K, Sv, alphap) {
    .Call(`_sparselca_update_eta`, K, Sv, alphap)
}

rg_check <- function(ap, bp) {
    .Call(`_sparselca_rg_check`, ap, bp)
}

update_class_probs_mvn_cp <- function(Y, KK, current_theta, current_Sigma, etav) {
    .Call(`_sparselca_update_class_probs_mvn_cp`, Y, KK, current_theta, current_Sigma, etav)
}

sample_S_mvn_mcmc <- function(Y, KK, current_Theta, current_Sigma, etav) {
    .Call(`_sparselca_sample_S_mvn_mcmc`, Y, KK, current_Theta, current_Sigma, etav)
}

update_theta_ind_mcmc <- function(YP, s, K, Sigma, mu0, B_inv) {
    .Call(`_sparselca_update_theta_ind_mcmc`, YP, s, K, Sigma, mu0, B_inv)
}

log_e0_gamma_ratio <- function(e0, e0_old, gamma, Kbig) {
    .Call(`_sparselca_log_e0_gamma_ratio`, e0, e0_old, gamma, Kbig)
}

log_eqd1_ratio <- function(e0, e0_old, cvec, Kbig) {
    .Call(`_sparselca_log_eqd1_ratio`, e0, e0_old, cvec, Kbig)
}

log_prior_ratio <- function(e0, e0_old, ae, be) {
    .Call(`_sparselca_log_prior_ratio`, e0, e0_old, ae, be)
}

log_conditional_likelihood_mvn_cp <- function(Y, K, Thetam, Sigmaa) {
    .Call(`_sparselca_log_conditional_likelihood_mvn_cp`, Y, K, Thetam, Sigmaa)
}

expected_log_likelihood_mvn_cp <- function(Y, T, K, Theta, Sigma) {
    .Call(`_sparselca_expected_log_likelihood_mvn_cp`, Y, T, K, Theta, Sigma)
}

expected_log_p_allocations <- function(Tmat, K, etav) {
    .Call(`_sparselca_expected_log_p_allocations`, Tmat, K, etav)
}

log_likelihood_mvn_cp <- function(Y, K, Thetam, Sigmaa, eta) {
    .Call(`_sparselca_log_likelihood_mvn_cp`, Y, K, Thetam, Sigmaa, eta)
}

